name: Quality Check

on:
  # Se ejecuta en cada push a la rama 'main'
  push:
    branches: [main]
  # También se ejecuta en cada pull request hacia 'main'
  pull_request:
    branches: [main]

jobs:
  # Nombre del trabajo que se va a ejecutar
  quality-check-job:
    # Se ejecuta en una máquina virtual de Ubuntu (la más reciente)
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Descarga tu código del repositorio a la máquina virtual
      - name: Checkout repository code
        uses: actions/checkout@v3

      # Paso 2: Configura el entorno de Flutter
      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0' # Asegúrate que coincida con tu versión o déjala así
          channel: 'stable'
          cache: true # Usa caché para acelerar futuras ejecuciones

      # Paso 3: Instala las dependencias de tu proyecto
      - name: Install dependencies
        run: flutter pub get

      # Paso 4: Analiza el código en busca de errores y advertencias
      - name: Analyze project source
        run: flutter analyze

      # Paso 5: Ejecuta las pruebas unitarias
      - name: Run unit tests
        run: flutter test