name: Quality Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      # 1. Clona el repositorio para que el workflow tenga acceso al código
      - uses: actions/checkout@v3

      # 2. Configura el entorno de Flutter con una versión específica
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'  # Puedes ajustar esto a la versión que usas
          channel: 'stable'
          cache: true # Habilita el caché para acelerar ejecuciones futuras

      # 3. Instala todas las dependencias del proyecto
      - name: Install dependencies
        run: flutter pub get

      # 4. Ejecuta el analizador de código estático de Flutter
      - name: Analyze
        run: flutter analyze

      # 5. Ejecuta todas las pruebas unitarias en la carpeta /test
      - name: Run tests
        run: flutter test