name: Quality Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      # 1. Descarga el código de tu repositorio
      - uses: actions/checkout@v3

      # 2. Configura una versión RECIENTE y ESTABLE de Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'  # <--- ¡AQUÍ ESTÁ EL CAMBIO IMPORTANTE!
          channel: 'stable'
          cache: true # Habilita el caché para acelerar ejecuciones

      # 3. Instala las dependencias del proyecto
      - name: Install dependencies
        run: flutter pub get

      # 4. Analiza el código para verificar buenas prácticas
      - name: Analyze
        run: flutter analyze

      # 5. Ejecuta las pruebas unitarias
      - name: Run tests
        run: flutter test
